### ISSUE TITLE
i followed your instruction and am facing this problem

### ISSUE THREAD

**Issue by BlockchainDeveloper009** [sozonome/nextarter-chakra#105]
I followed your instructions in Readme.md, am facing below problem when i run "yarn dev". please note that after cloning your project i did not do "npm install", still npx command worked to create my project.(petvet)
```
PS C:\Repository\learnWeb3Dao\r1\UI-Ref\ui_fmt1\petvet> yarn dev
yarn run v1.22.17
$ next dev
'next' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by sozonome** [comment]
Hi @BlockchainDeveloper009 this is the same exact issue as https://github.com/sozonome/nextarter-chakra/issues/96

I already updated the README since then to clarify. Please carefully read the instructions here: https://github.com/sozonome/nextarter-chakra#getting-started

It's common in nodejs based project that we need to install the required modules / dependencies first in order to run the project.
